version: "2"
services:
  web:
    build: .
    image: studyup
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules

    ports:
    - "3000:3000"


  mongo:
    image: "mongo"
    ports:
      - "21017:27017"


  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"



